name: client_api
description: "Client API en Dart pour interagir avec le serveur Node.js"
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.6 # Librairie pour effectuer des requêtes HTTP

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
